kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/api
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: api
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to [space.s.][rootSpace.]api.<random suffix>.<region>.azds.io
      - $(spacePrefix)$(rootSpacePrefix)api$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      sync:
      - "!**/package.json"
      iterate:
        processesToKill: [node]